### PR TITLE
Add repository for latest version

### PR DESCRIPTION
**Pull request by ifdattic**
As mentioned in https://github.com/phansible/phansible/issues/269

### CODE REVIEW

**Comment by debo** [comment]
@ifdattic thanks for yout contribution, can you make sure the build is passing otherwise I can't merge this one. Thanks a lot.

**Comment by ifdattic** [comment]
OK, from that I understand it fails because the template uses the variables and the role has no variables defined (variables are defined in phansible when you generate the package for everything). Looking at the Apache (and other roles) it looks like they define some defaults for those values. Will add them later then.

**Comment by debo** [comment]
@ifdattic yes that's correct, we are working to have all the playbooks not being strictly coupled with the phansible website so we are slowly extracting and fixing them as we come along problems. Also have a look at other working playbooks to say how we handle some basic tests to ensure the playbook is working and idempotency is guaranteed. If you don't understand much of this and need any help don't be afraid to ask, I'll be more than happy to support.

Once again thanks for your help.

**Comment by debo** [comment]
@ifdattic sorry I did miss this. Thanks for fixing the build and the PR, mergin...

**Comment by ifdattic** [comment]
Glad to help!

**Pull request merged**
